---
- name: Install Fedora dnf packages
  ansible.builtin.dnf:
    name:
      - ansible-core
      - bat
      - fastfetch
      - figlet
      - fzf
      - gh
      - golangci-lint
      - htop
      - helm
      - k9s
      - neovim
      - pre-commit
      - rclone
      - ripgrep
      - vim-enhanced
      - yq
      - zoxide
      - zsh
    state: latest
