---
- name: Add dnf repositories
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    mode: '0644'
  loop:
    - name: mullvad
      url: https://repository.mullvad.net/rpm/stable/mullvad.repo
    - name: tailscale
      url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  loop_control:
    label: "{{ item.name }}"

- name: Install Fedora dnf packages
  become: true
  ansible.builtin.dnf:
    name:
      - ansible-core
      - bat
      - distrobox
      - fastfetch
      - figlet
      - fzf
      - gh
      - golangci-lint
      - htop
      - helm
      - k9s
      - mullvad-vpn
      - neovim
      - podman-docker
      - pre-commit
      - rclone
      - ripgrep
      - tailscale
      - vim-enhanced
      - yq
      - zoxide
      - zsh
    state: latest
