- name: Set hostname
  become: yes
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: systemd

- name: Set time zone
  become: yes
  ansible.builtin.timezone:
    name: "{{ timezone }}"

- name: Set system locale
  ansible.builtin.command: localectl set-locale LANG={{ locale }}

- name: Create message of the day file
  ansible.builtin.copy:
    dest: /etc/motd
    content: |
      Successfully logged into your homelab
    mode: "0644"
