---
- name: Checkout dotfiles repo
  ansible.builtin.git:
    repo: "https://{{ github_username }}@github.com/{{ github_username }}/dotfiles.git"
    version: main
    dest: "{{ ansible_facts['env']['HOME'] }}/dotfiles"
    force: true
