---
- name: Enable podman user socket
  ansible.builtin.systemd:
    name: podman.socket
    scope: user
    enabled: true
    state: started

- name: Add podman environment variables system-wide
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/podman-k3d.sh
    mode: '0644'
    content: |
      export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
      export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
      export DOCKER_SOCK=$XDG_RUNTIME_DIR/podman/podman.sock

- name: Create k3d podman network
  containers.podman.podman_network:
    name: k3d
    state: present
