- name: Ensure git is installed
  ansible.builtin.command: nix-env -iA nixpkgs.git
  args:
    creates:
      - "{{ nix_bin_dir }}/git"

- name: Configure global Git config
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "user.name", value: "Ryan Hynes" }
    - { name: "user.email", value: "131348960+rmjhynes@users.noreply.github.com" }
    - { name: "url.git@github.com:.insteadof", value: "https://github.com/" }
    - { name: "init.defaultBranch", value: "main" }
    - { name: "push.autosetupremote", value: "true" }
    - { name: "core.editor", value: "nvim" }
    - { name: "alias.st", value: "status" }
    - { name: "alias.sw", value: "switch" }
    - { name: "alias.d", value: "diff" }
    - { name: "alias.c", value: "commit" }
    - { name: "alias.rb", value: "rebase" }

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if SSH key already exists
  ansible.builtin.stat:
    path: "{{ ssh_key_path }}"
  register: ssh_key_stat

- name: Generate SSH key pair if not already present
  community.crypto.openssh_keypair:
    path: "{{ ssh_key_path }}"
    type: ed25519
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    comment: "github-{{ ansible_user }}-{{ ansible_date_time.iso8601 }}"
  when: not ssh_key_stat.stat.exists

- name: Add GitHub configuration to SSH config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    block: |
      Host github.com
        HostName github.com
        User git
        IdentityFile ~/.ssh/github_ed25519
        IdentitiesOnly yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - GitHub Config"
    create: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Retrieve public key content
  ansible.builtin.command: "cat {{ ssh_key_path }}.pub"
  register: pubkey_content
  changed_when: false

- name: Add SSH key to GitHub
  community.general.github_key:
    name: "{{ ansible_user }}@homelab ({{ ansible_date_time.date }})"
    token: "{{ github_pat_token }}"
    pubkey: "{{ pubkey_content.stdout }}"
  when:
    - not ssh_key_stat.stat.exists # Only if the ssh key did not already exist
    - github_pat_token is defined
    - github_pat_token | length > 0

- name: Print public key if GitHub token not set
  ansible.builtin.debug:
    msg: |
      GitHub token not provided. Manually add this key to GitHub: {{ pubkey_content.stdout }}
  when: github_pat_token is not defined or github_pat_token | length == 0

- name: Test GitHub SSH connection
  ansible.builtin.command: ssh -T git@github.com
  register: github_connection_test_result
  changed_when: false
  failed_when: "'successfully authenticated' not in result.stderr"
  ignore_errors: true
  when:
    - github_pat_token is defined
    - github_pat_token | length > 0

- name: Ensure .gnupg directory exists with proper permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0700"
    recurse: true # Ensures all internal files/directories are writable

- name: Fix permissions for GPG directories and files
  ansible.builtin.file:
    path: "{{ gpg_dir_path }}/{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "private-keys-v1.d"
      mode: '0700'
      state: directory
    - path: "sshcontrol"
      mode: '0600'
      state: file

- name: Ensure ~/.gnupg/common.conf is empty
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.gnupg/common.conf"
    content: "" # This creates/overwrites the file with empty content
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Kill keyboxd process if running
  ansible.builtin.command: pkill -f keyboxd
  register: pkill_result
  changed_when: false
  failed_when: pkill_result.rc > 1 # Treat rc=0 (killed) and rc=1 (not running) as success; fail only on real errors

- name: Find pinentry program on the target
  ansible.builtin.command: which pinentry
  register: pinentry_path
  changed_when: false
  failed_when: pinentry_path.rc != 0 and pinentry_path.stdout == ""

- name: Configure GPG Agent
  ansible.builtin.copy:
    dest: "{{ gpg_dir_path }}/gpg-agent.conf"
    mode: '0600'
    content: |
      pinentry-program {{ pinentry_path.stdout }}

- name: Restart GPG Agent
  ansible.builtin.command: gpgconf --kill gpg-agent
  changed_when: false

- name: Copy GPG batch file
  ansible.builtin.copy:
    src: "{{ gpg_file }}"
    dest: "{{ gpg_file_path }}"
    mode: '0600'

- name: Check if GPG key already exists
  ansible.builtin.command: gpg --list-secret-keys --keyid-format=long 131348960+rmjhynes@users.noreply.github.com
  register: gpg_check
  ignore_errors: true # Throws error even when key exists
  changed_when: false

- name: Delete any lock files (prevents 'database_open waiting for lock' error)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ gpg_dir_path }}/*.lock"
    - "{{ gpg_dir_path }}/public-keys.d"
  register: delete_result
  when: gpg_check.rc != 0

- name: Generate signing-only GPG key if it doesn't already exist
  ansible.builtin.command: gpg --batch --generate-key {{ gpg_file_path }}
  register: gpg_generate_result
  changed_when: gpg_generate_result.rc == 0 and gpg_check.rc != 0
  when: gpg_check.rc != 0

- name: Extract GPG key ID
  ansible.builtin.command: "gpg --list-secret-keys --batch --with-colons --status-fd 1 | awk -F: '/^sec/ {print $5}'"
  register: gpg_keyid
  changed_when: false
  when: gpg_check.rc != 0

- name: Print GPG key
  ansible.builtin.debug:
    msg: |
      {{ gpg_keyid.stdout }}
  when: gpg_keyid.stdout is defined and gpg_keyid.stdout != ""

- name: Export GPG key
  ansible.builtin.command: gpg --armor --export {{ gpg_keyid.stdout }}
  register: exported_key
  changed_when: false
  failed_when: exported_key.rc != 0
  when: gpg_keyid.stdout is defined and gpg_keyid.stdout != ""
