- name: Install K3s
  become: yes
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: chmod kube config file for sudo-less kubectl
  become: yes
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    mode: '0644'

- name: Verify K3s is running
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: yes

- name: Get K3s version
  command: /usr/local/bin/k3s --version
  register: k3s_version
  changed_when: false

- name: Display K3s version
  ansible.builtin.debug:
    var: k3s_version.stdout_lines

- name: Get cluster info
  command: /usr/local/bin/kubectl cluster-info
  register: cluster_info
  changed_when: false

- name: Display cluster info
  ansible.builtin.debug:
    var: cluster_info.stdout_lines
