- name: Get mullvad-daemon path
  ansible.builtin.command: which mullvad-daemon
  register: mullvad_path
  changed_when: false
  failed_when: mullvad_path.rc != 0

- name: Print mullvad-daemon path
  ansible.builtin.debug:
    var: mullvad_path.stdout

- name: Check if mullvad-daemon is already running
  ansible.builtin.command: pgrep -f mullvad-daemon
  register: mullvad_daemon_process
  changed_when: false
  ignore_errors: true  # If not running, pgrep exits with rc=1

# The Mullvad daemon is run in the foreground therefore wait for it to start
# and move onto the next task
- name: Start mullvad-daemon
  become: true
  ansible.builtin.command: "{{ mullvad_path.stdout }}"
  async: 5 # Run the task asynchronously on the remote host for up to 5 seconds
  poll: 0 # Do not wait for the task to finish; return immediately so Ansible can continue
  changed_when: false
  when: mullvad_daemon_process.rc != 0  # Only run if daemon is not already running

# Same as piping account number into `mullvad account login` command
- name: Log into Mullvad
  ansible.builtin.command: mullvad account login
  args:
    stdin: "{{ mullvad_account_number }}"
  register: mullvad_login
  changed_when: mullvad_login.rc == 0
  failed_when: mullvad_login.rc != 0

- name: Get Mullvad Account Info
  ansible.builtin.command: mullvad account get
  register: mullvad_account_info
  changed_when: false
  failed_when: mullvad_account_info.rc != 0

- name: Print Mullvad account info
  ansible.builtin.debug:
    var: mullvad_account_info.stdout_lines
