---
- name: Log into Mullvad
  ansible.builtin.command: mullvad account login {{ mullvad_account_number }}
  register: mullvad_login
  changed_when: mullvad_login.rc == 0
  failed_when: mullvad_login.rc != 0

- name: Get Mullvad Account Info
  ansible.builtin.command: mullvad account get
  register: mullvad_account_info
  changed_when: false
  failed_when: mullvad_account_info.rc != 0

- name: Print Mullvad account info
  ansible.builtin.debug:
    var: mullvad_account_info.stdout_lines
