- name: Find Mullvad path
  ansible.builtin.command: which mullvad-daemon
  register: mullvad_path

- name: Get Mullvad path
  ansible.builtin.debug:
    var: mullvad_path.stdout

- name: Start mullvad-daemon
  become: true
  ansible.builtin.command: "{{ mullvad_path.stdout }}"
  async: 5
  poll: 0
