---
- name: Download Starship install script
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship-install.sh
    mode: "0755"

- name: Install Starship prompt
  become: true
  ansible.builtin.command:
    cmd: /tmp/starship-install.sh -y
    creates: /usr/local/bin/starship
