- name: Check if Nix package manager is installed
  ansible.builtin.stat:
    path: /nix
  register: nix_dir

- name: Install Nix package manager (multi-user, non-interactive)
  become: true
  ansible.builtin.shell: |
    sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --daemon --yes
  args:
    creates: /nix
    executable: /bin/bash
  when: not nix_dir.stat.exists

- name: Ensure .config/nixpkgs directory exists to store Nix packages file
  become: true
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/nixpkgs"
    state: directory
    mode: '0755'
