name: "Pre-merge checks"

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run Ansible lint
        uses: rmjhynes/github-actions/ansible-lint@main

  run-shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Run Shellcheck
        uses: rmjhynes/github-actions/shellcheck@main
